language: go

go:
    - 1.6
    - 1.7
    - tip
before_install:
    - go get gopkg.in/urfave/cli.v2
    - go get gopkg.in/yaml.v2
    - go get github.com/fatih/color
matrix:
  allow_failures:
    - go: tip